
import type { SnackTypeInfo } from './types';

export const KSNACK_TYPES: SnackTypeInfo[] = [
  {
    id: 'A',
    vibe: '강렬한 중독성',
    vibe_en: 'Intense & Addictive',
    snack: '매운 새우깡',
    snack_en: 'Spicy Shrimp Crackers',
    stars: '(여자)아이들 소연, 현아, BTS 정국',
    stars_en: '(G)I-DLE Soyeon, Hyuna, BTS Jungkook',
    definition: '한번 빠지면 헤어날 수 없는 마성의 매력. 시선이 닿는 순간 주변을 압도하는 강력한 포스와 독보적인 카리스마.',
    definition_en: "An irresistible charm that's hard to escape. Your powerful presence and unique charisma captivate everyone around you the moment they see you.",
    colorClass: 'text-red-500',
  },
  {
    id: 'B',
    vibe: '부드럽고 달콤함',
    vibe_en: 'Soft & Sweet',
    snack: '허니버터칩',
    snack_en: 'Honey Butter Chip',
    stars: '박보검, 아이유, NCT 재현',
    stars_en: 'Park Bo-gum, IU, NCT Jaehyun',
    definition: '보는 이에게 힐링을 선사하는 천상의 미소. 맑고 따뜻함을 잃지 않는 부드러운 분위기, 누구나 기댈 수 있는 편안함과 달콤함.',
    definition_en: 'A heavenly smile that brings healing to others. Your warm, gentle aura and sweet comfort make everyone feel at ease.',
    colorClass: 'text-yellow-400',
  },
  {
    id: 'C',
    vibe: '새콤 톡톡 개성파',
    vibe_en: 'Zesty & Unique',
    snack: '자유시간',
    snack_en: 'Jayu Sigan (Free Time)',
    stars: '세븐틴 부승관, 이영지, 이광수',
    stars_en: 'SEVENTEEN Seungkwan, Lee Young-ji, Lee Kwang-soo',
    definition: '예측 불가능한 유쾌함. 틀에 갇히지 않은 톡톡 튀는 아이디어와 넘치는 에너지. 지루할 틈 없이 주변을 즐겁게 하는 독특한 존재감.',
    definition_en: 'Unpredictably delightful. You have boundless energy and quirky ideas that break the mold, keeping everyone entertained with your unique presence.',
    colorClass: 'text-lime-500',
  },
  {
    id: 'D',
    vibe: '균형 잡힌 클래식함',
    vibe_en: 'Balanced & Classic',
    snack: '새우깡',
    snack_en: 'Shrimp Crackers',
    stars: '이정재, 김혜수, 엑소 수호',
    stars_en: 'Lee Jung-jae, Kim Hye-soo, EXO Suho',
    definition: '시간이 지나도 변치 않는 정석적인 아름다움과 안정감. 겉은 차분하지만 깊이 있는 신뢰감과 기품이 느껴져 언제나 호감을 주는 타입.',
    definition_en: 'A timeless, classic beauty and sense of stability. Your calm exterior holds a deep trustworthiness and elegance that is always appealing.',
    colorClass: 'text-blue-400',
  },
  {
    id: 'E',
    vibe: '깊고 복합적인 풍미',
    vibe_en: 'Deep & Complex',
    snack: '꼬북칩',
    snack_en: 'Kkobuk Chip (Turtle Chip)',
    stars: '김태리, 유아인, BTS RM',
    stars_en: 'Kim Tae-ri, Yoo Ah-in, BTS RM',
    definition: '쉽게 정의할 수 없는 오묘한 매력. 겉모습보다 내면에 더 많은 이야기와 깊이를 품고 있어, 알면 알수록 새로운 복합적인 풍미.',
    definition_en: "A mysterious charm that's hard to define. There's more to you than meets the eye, with a deep inner world that reveals new layers over time.",
    colorClass: 'text-purple-400',
  },
  {
    id: 'F',
    vibe: '바삭! 경쾌한 활동성',
    vibe_en: 'Crispy & Energetic',
    snack: '포카칩',
    snack_en: 'Poca Chip',
    stars: '아이브 장원영, 배우 최우식, TXT 수빈',
    stars_en: 'IVE Jang Won-young, Actor Choi Woo-shik, TXT Soobin',
    definition: '맑고 밝은 기운을 전달하는 트렌디세터. 활기차고 당당한 모습으로 시선을 사로잡으며, 등장하는 순간 분위기는 생기로 가득 차 오름.',
    definition_en: 'A trendsetter who radiates bright, positive energy. Your vibrant and confident style captures attention, filling the room with life the moment you enter.',
    colorClass: 'text-sky-400',
  },
  {
    id: 'G',
    vibe: '쫀득! 끈기 있는 노력형',
    vibe_en: 'Chewy & Persistent',
    snack: '마이쮸',
    snack_en: 'Mychew',
    stars: '유노윤호, 김연아, 배우 조정석',
    stars_en: 'U-Know Yunho, Yuna Kim, Actor Jo Jung-suk',
    definition: '포기하지 않는 단단한 끈기와 집중력. 목표를 향해 묵묵히 나아가는 모습에서 프로페셔널한 아우라가 느껴지며, 함께 하는 사람들에게 믿음을 줌.',
    definition_en: 'Unwavering persistence and focus. Your quiet determination towards your goals creates a professional aura that inspires trust in those around you.',
    colorClass: 'text-orange-500',
  },
  {
    id: 'H',
    vibe: '촉촉한 반전 매력',
    vibe_en: 'Moist & Unexpected Charm',
    snack: '초코파이',
    snack_en: 'Choco Pie',
    stars: '차은우, 김선호, 아이유',
    stars_en: 'Cha Eun-woo, Kim Seon-ho, IU',
    definition: '겉과 속이 다른 반전의 매력. 차가워 보이던 인상 뒤에 숨겨진 따뜻하고 감성적인 면모가 예상치 못한 순간에 큰 감동을 선사함.',
    definition_en: "A surprising charm that's different inside and out. Behind a seemingly cool impression lies a warm, emotional side that touches people unexpectedly.",
    colorClass: 'text-pink-400',
  },
  {
    id: 'I',
    vibe: '달콤 쌉쌀한 성숙미',
    vibe_en: 'Bittersweet & Mature',
    snack: '빈츠',
    snack_en: 'Binch',
    stars: '공유, 전지현, 엑소 카이',
    stars_en: 'Gong Yoo, Jun Ji-hyun, EXO Kai',
    definition: '삶의 깊이가 느껴지는 성숙하고 우아한 분위기. 낭만적이지만 절제된 지적인 매력이 돋보이며, 커피 같은 깊은 여운을 남김.',
    definition_en: 'A mature and elegant aura that hints at a deep life experience. Your romantic yet restrained intellectual charm leaves a lasting, coffee-like impression.',
    colorClass: 'text-amber-600',
  },
  {
    id: 'J',
    vibe: '든든한 포용력',
    vibe_en: 'Hearty & Inclusive',
    snack: '오징어땅콩',
    snack_en: 'Squid Peanut',
    stars: '유재석, 마동석, 송중기',
    stars_en: 'Yoo Jae-suk, Ma Dong-seok, Song Joong-ki',
    definition: '모두를 아우르는 넓고 넉넉한 마음을 지닌 리더형 인상. 힘들 때 기댈 수 있는 편안하고 든든한 존재감으로, 안정과 활력을 동시에 제공함.',
    definition_en: 'A leader with a big heart, embracing everyone. You are a reliable and comforting presence people can lean on, providing both stability and energy.',
    colorClass: 'text-green-500',
  },
];
